//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.ProjectApi.ServiceManagement.SDM
{
	using System;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.ProjectApi.ServiceManagement.API.Relationship;

	/// <summary>
	/// Exposer-metods for the <see cref="Models.Link"/> instances.
	/// </summary>
	public static class LinkExposers
	{
		public static readonly Exposer<Models.Link, Guid> Guid = new Exposer<Models.Link, Guid>((obj) => obj.ID, String.Join(".", nameof(LinkExposers), nameof(Guid)));
		public static readonly Exposer<Models.Link, string> ChildID = new Exposer<Models.Link, string>((obj) => obj.ChildID, String.Join(".", nameof(LinkExposers), nameof(ChildID)));
		public static readonly Exposer<Models.Link, string> ChildName = new Exposer<Models.Link, string>((obj) => obj.ChildName, String.Join(".", nameof(LinkExposers), nameof(ChildName)));
		public static readonly Exposer<Models.Link, string> ParentID = new Exposer<Models.Link, string>((obj) => obj.ParentID, String.Join(".", nameof(LinkExposers), nameof(ParentID)));
		public static readonly Exposer<Models.Link, string> ParentName = new Exposer<Models.Link, string>((obj) => obj.ParentName, String.Join(".", nameof(LinkExposers), nameof(ParentName)));
	}
}