//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Dom Code Generator automation script.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.ProjectApi.ServiceManagement.SDM
{
	using System;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.ProjectApi.ServiceManagement.API.PeopleAndOrganization;

	/// <summary>
	/// Exposer-metods for the <see cref="Models.Organization"/> instances.
	/// </summary>
	public static class OrganizationExposers
	{
		public static readonly Exposer<Models.Organization, Guid> Guid = new Exposer<Models.Organization, Guid>((obj) => obj.ID, String.Join(".", nameof(OrganizationExposers), nameof(Guid)));
		public static readonly Exposer<Models.Organization, string> Name = new Exposer<Models.Organization, string>((obj) => obj.Name, String.Join(".", nameof(OrganizationExposers), nameof(Name)));
		public static readonly Exposer<Models.Organization, Guid> Category = new Exposer<Models.Organization, Guid>((obj) => obj.CategoryId ?? System.Guid.Empty, String.Join(".", nameof(OrganizationExposers), nameof(Category)));
	}

	/// <summary>
	/// Exposer-metods for the <see cref="Models.People"/> instances.
	/// </summary>
	public static class PeopleExposers
	{
		public static readonly Exposer<Models.People, Guid> Guid = new Exposer<Models.People, Guid>((obj) => obj.ID, String.Join(".", nameof(PeopleExposers), nameof(Guid)));
		public static readonly Exposer<Models.People, string> Name = new Exposer<Models.People, string>((obj) => obj.FullName, String.Join(".", nameof(PeopleExposers), nameof(Name)));
		public static readonly Exposer<Models.People, Guid> Organization = new Exposer<Models.People, Guid>((obj) => obj.OrganizationId ?? System.Guid.Empty, String.Join(".", nameof(PeopleExposers), nameof(Organization)));
		public static readonly Exposer<Models.People, Guid> Experience = new Exposer<Models.People, Guid>((obj) => obj.ExperienceLevel?.ID ?? System.Guid.Empty, String.Join(".", nameof(PeopleExposers), nameof(Experience)));
	}

	/// <summary>
	/// Exposer-metods for the <see cref="Models.Category"/> instances.
	/// </summary>
	public static class CategoryExposers
	{
		public static readonly Exposer<Models.Category, Guid> Guid = new Exposer<Models.Category, Guid>((obj) => obj.ID, String.Join(".", nameof(CategoryExposers), nameof(Guid)));
		public static readonly Exposer<Models.Category, string> Name = new Exposer<Models.Category, string>((obj) => obj.Name, String.Join(".", nameof(CategoryExposers), nameof(Name)));
	}

	/// <summary>
	/// Exposer-metods for the <see cref="Models.ExperienceLevel"/> instances.
	/// </summary>
	public static class ExperienceLevelExposers
	{
		public static readonly Exposer<Models.ExperienceLevel, Guid> Guid = new Exposer<Models.ExperienceLevel, Guid>((obj) => obj.ID, String.Join(".", nameof(ExperienceLevelExposers), nameof(Guid)));
		public static readonly Exposer<Models.ExperienceLevel, string> Value = new Exposer<Models.ExperienceLevel, string>((obj) => obj.Value, String.Join(".", nameof(ExperienceLevelExposers), nameof(Value)));
	}
}